version: "2"

services:
  python-app:
    image: nrb-python-unoconv
    volumes:
      - ./:/app
      - /samba/shares/production/Boats on Order - Smartsheet edition/:/output
    entrypoint: [python, smartsheet_boats_on_order.py]
